# 备用方案，如果修改不了 helm chart，则使用此文件
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: devops
  labels:
    app: jenkins
spec:
  type: NodePort 
  ports:
    - name: jenkins
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    app: app.kubernetes.io/name=jenkins # 匹配 helm chart 的标签
